name = "Calculator"
uuid = "A5611436-126E-4520-AA4A-B6E7865E0FB2"
authors = ["Your Name <your@email.com>"]
version = "0.1.0"

[deps]
# Dependencies, if any, will be listed here

[compat]
julia = "1.6"  # Minimum Julia version required by the package
